version: "3.9"

services:
  api:
    build: ./app/api
    container_name: datapress-api
    ports:
      - "8080:8000"
    restart: unless-stopped

  front:
    build: ./app/front
    container_name: datapress-front
    ports:
      - "8081:80"
    depends_on:
      - api
    restart: unless-stopped
