apiVersion: v1
kind: Service
metadata:
  name: datapress-api
  namespace: datapress-recette
spec:
  selector:
    app: datapress-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
