apiVersion: v1
kind: Secret
metadata:
  name: datapress-secret
  namespace: datapress-recette
type: Opaque
data:
  # "super-secret-password" en base64 => c3VwZXItc2VjcmV0LXBhc3N3b3Jk
  DB_PASSWORD: "c3VwZXItc2VjcmV0LXBhc3N3b3Jk"
